name: docs

on:
  push:
    branches:
      - develop
      - master

env:
  JDOC_APP_ID: "fdb282ef-1a12-4ed8-8859-ac16c5ea3390"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Set env to develop
      if: endsWith(github.ref, '/develop')
      run: |
        echo "::set-env name=JDOC_ADOC_APP_ID::fdb282ef-1a12-4ed8-8859-ac16c5ea3390"
    - name: Set env to master
      if: endsWith(github.ref, '/master')
      run: |
        echo "::set-env name=JDOC_APP_ID::131e893c-eac4-4713-917b-a49fdd10c1c8"
    - name: build jsdoc
      run: |
        cd doc/jsdoc/
        npm install
        npx documentation build ../../../cables/src/core/index.js -f html -o out --theme theme
    - name: Deploy jsdocs to netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ env.JDOC_APP_ID }}
      with:
        args: deploy --dir=doc/jsdoc/out --prod
        secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
