name: docs

on:
  push:
    branches:
      - docdeploy

env:
  JSDOC_LIVE_HOST: 'jsdoc.cables.gl'
  JSDOC_DEV_HOST: 'jsdoc.dev.cables.gl'
  DOC_LIVE_HOST: 'doc.cables.gl'
  DOC_DEV_HOST: 'doc.dev.cables.gl'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build gitbook
      run: |
        cd doc/gitbook/
        npm install -g gitbook-cli
        gitbook install
        npx gitbook build
    - name: build jsdoc
      run: |
        cd doc/jsdoc/
        npx documentation build ../../../cables/src/core/index.js -f html -o out --theme theme
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: deploy jsdocs
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ env.JSDOC_DEV_HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
      with:
        source: "doc/jsdoc/*"
        target: "jsdoc"
