name: docs

on:
  push:
    branches:
      - docdeploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build gitbook
      run: |
        doc/gitbook/
        npm install -g gitbook-cli
        gitbook install
        npx gitbook build
    - name: build jsdoc
      run: |
        cd doc/jsdoc/
        npx documentation build ../../../cables/src/core/index.js -f html -o out --theme theme
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/scp-action@master
    - name: deploy jsdocs
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
      with:
        source: "doc/jsdoc/*"
        target: "jsdoc"
